### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'`

### ISSUE THREAD

**Issue by stonez56** [CodeReclaimers/neat-python#130]
I tried the xor example: [path>python3 evolve-feedforward.py]
and always got error as below output:

The script couldn't find "dot" in the system path. I have installed graphviz and pydot library in this Mac.
What could be the problem?

Neat-python-0.92
Mac: High Sierra OS
Python: V3.6
 
`Output:
input (0.0, 0.0), expected output (0.0,), got [0.05886658735995552]
input (0.0, 1.0), expected output (1.0,), got [0.9545453636148662]
input (1.0, 0.0), expected output (1.0,), got [0.9977905063580692]
input (1.0, 1.0), expected output (0.0,), got [0.240927833492194]
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/graphviz/backend.py", line 124, in render
    subprocess.check_call(args, startupinfo=STARTUPINFO, stderr=stderr)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'`

**Comment by stonez56** [comment]
I figured this out on my Mac. It turned out I didn't install graphviz library correctly.

After doing this:
`path>brew install graphviz`
The xor example runs correctly!
