### ISSUE TITLE
XOR example doesn't work

### ISSUE THREAD

**Issue by Ploppz** [CodeReclaimers/neat-python#161]
When I try to run `evolve-feedforward-parallel.py`, I get:
```
Traceback (most recent call last):
  File "evolve-feedforward-parallel.py", line 93, in <module>
    run(config_path)
  File "evolve-feedforward-parallel.py", line 55, in run
    config = neat.Config(neat.DefaultGenome, neat.DefaultReproduction,
AttributeError: module 'neat' has no attribute 'Config'
```

**Comment by rmyhovych** [comment]
Can confirm, I have the same error

**Comment by techwithtim** [comment]
I received this error as well

**Comment by RiwEZ** [comment]
I have this error too. It makes me curious, Is it about our pc that was wrong?

**Comment by yfe404** [comment]
Same error...

**Comment by Flamyng0** [comment]
Has someone found a fix for this?
