### ISSUE TITLE
Error in examples-single-pole-balancing\test-feedforward.py 

### ISSUE THREAD

**Issue by tahoemike** [CodeReclaimers/neat-python#284]
Running test-feedforward.py results in the following error:
C:\Users\tahoemike\Documents\Studies\Code\neat-python-master\examples\single-pole-balancing>python test-feedforward.py
Traceback (most recent call last):
  File "C:\Users\tahoemike\Documents\Studies\Code\neat-python-master\examples\single-pole-balancing\test-feedforward.py", line 10, in <module>
    from movie import make_movie
  File "C:\Users\tahoemike\Documents\Studies\Code\neat-python-master\examples\single-pole-balancing\movie.py", line 2, in <module>
    import moviepy.editor as mpy
ModuleNotFoundError: No module named 'moviepy.editor'

The line 
  import moviepy.editor as mpy 
in the file movie.py needs to be changed to:
  import moviepy as mpy

Then the program produces a cart balancing movie as expected.  

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome 123.0.6312.122

**Comment by CodeReclaimers** [comment]
Thanks!
