### ISSUE TITLE
issue with evolve-feedforward-parallel.py

### ISSUE THREAD

**Issue by unnir** [CodeReclaimers/neat-python#65]
So, don't judge me guys, I am new to neuron stuff... 

I start the evolve-feedforward-parallel.py, however I got this error message:

```
Traceback (most recent call last):
  File "/Users/vadimborisov/anaconda/lib/python3.5/site-packages/graphviz/backend.py", line 95, in render
    subprocess.call(args, startupinfo=STARTUPINFO)
  File "/Users/vadimborisov/anaconda/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/vadimborisov/anaconda/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/Users/vadimborisov/anaconda/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'dot'
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/Users/vadimborisov/Documents/neat-python/examples/xor/evolve-feedforward-parallel.py", line 93, in <module>
    run(config_path)
  File "/Users/vadimborisov/Documents/neat-python/examples/xor/evolve-feedforward-parallel.py", line 82, in run
    visualize.draw_net(config, winner, True, node_names = node_names)
  File "/Users/vadimborisov/Documents/neat-python/examples/xor/visualize.py", line 198, in draw_net
    dot.render(filename, view=view)
  File "/Users/vadimborisov/anaconda/lib/python3.5/site-packages/graphviz/files.py", line 146, in render
    rendered = backend.render(self._engine, self._format, filepath)
  File "/Users/vadimborisov/anaconda/lib/python3.5/site-packages/graphviz/backend.py", line 100, in render
    'are on your systems\' path' % args)
RuntimeError: failed to execute ['dot', '-Tsvg', '-O', 'Digraph.gv'], make sure the Graphviz executables are on your systems' path
```

So, what should I do? *google didn't really help

**Comment by unnir** [comment]
The issue has been solved.

The solution is to install graphviz using conda.

Sorry.

**Comment by CodeReclaimers** [comment]
No worries--graphviz has given several people troubles because it doesn't always seem to get installed correctly.

**Comment by unnir** [comment]
but the graphviz is a really nice addition to the script.
